
### get all records (books)
GET http://localhost:3001/books HTTP/1.1
Content-Type: application/json

### create record
POST http://localhost:3001/books HTTP/1.1
Content-Type: application/json

{
    "title": "Harry Potter"
}

### update record 
PUT  http://localhost:3001/books/1 HTTP/1.1
Content-Type: application/json

{
    "title": "Dark Tower"
}

###
### delete record
DELETE http://localhost:3001/books/1 HTTP/1.1
Content-Type: application/json